name: OpenWrt Build

on:
  push:
    branches:
      - openwrt-24.10
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: openwrt-24.10

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libncurses5-dev gawk git gettext libssl-dev xsltproc wget unzip python3

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure
        run: |
          cp config.seed .config
          make defconfig

      - name: Select iptables-mod-extra
        run: |
          sed -i 's/# CONFIG_IPTABLES_MODULES_EXTRA is not set/CONFIG_IPTABLES_MODULES_EXTRA=y/' .config

      - name: Download packages
        run: make download

      - name: Compile iptables-mod-extra
        run: make package/iptables-mod-extra/compile V=s

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: iptables-mod-extra-build
          path: bin/targets/x86/64/packages/
